### ISSUE TITLE
Simplify `CONTRIBUTING.md` process

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-registry#111]
Currently the [`CONTRIBUTING.md`](https://github.com/ethereum-optimism/superchain-registry/blob/46f8c2f74debd4a40facf5686b2238cf7093023c/CONTRIBUTING.md) process has a lot of manual steps and is tedious.

None of the inputs to this process are secret, so we can commit inputs to the repo as an incremental step towards a broader refactor of the registry. Therefore the proposed implementation here is:

- Create a `superchain/input/template.toml` file that has all the keys needed
- Add [yq](https://github.com/mikefarah/yq) or [yj](https://github.com/sclevine/yj) as a dependency. (yq parses TOML directly, yj converts it to json so we can pipe to jq)
- Create a `scripts/add-chain.sh` bash script that contains all the existing code currently in `CONTRIBUTING.md`, with yq/yj usage as needed

Now to add a chain you would:
- `cp superchain/input/template.toml superchain/input/{l1ChainName}/{l2ChainName}.toml`
    - Example: `cp superchain/input/template.toml superchain/input/sepolia/mode.toml`
- Fill in the resulting file
- Run `bash scripts/add-chain.sh [path/to/your/input.toml]`

Then to verify new inputs on PRs, CI run the bash script for new input files (or all inputs if its simpler), and verify there is no resulting diff (similar to how our snapshots work in the monorepo)

Alternatively, if we don't want to introduce TOML parsing yet, we can use a `.env.example` file and just export env vars

**Comment by mds1** [comment]
Yea that's fair. I do like the idea of using this issue as a step towards a dedicated `input` directory, and to your point `DEPLOYMENTS_DIR` is really not the input we care about—the contract addresses it holds are. So perhaps we do use env vars, and use those env vars to also generate the input file.

I'm also ok with keeping it simple and removing the input file approach for now if we think it's too early

**Comment by geoknee** [comment]
Got a straw man implementation here https://github.com/ethereum-optimism/superchain-registry/pull/118 

Happy to go after TOML and other refactors too, but that might be best broken up and done in follow ups?

**Comment by mds1** [comment]
Let's mark this as completed by #118 for now, and we can revisit pending feedback
