### ISSUE TITLE
Improve hardfork timestamp override handling in add-chain.sh

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#166]
Desiderata for improvements here:
* we pipe the values through `date -r <timestamp> -u ` and append this as a comment on each line, so it matches: 
https://github.com/ethereum-optimism/superchain-registry/blob/119f493760a5d2de4c9cb878dcfa03077e24d2bc/superchain/configs/sepolia/superchain.yaml#L10-L12
* we iterate through all fields ending in `_time`, to catch future hardforks without needing to update the script
* instead of filling with `null` when the `jq` query fails, we should use `nil` or even better just omit the entire line from the output yaml file. 
* EDIT: if the timestamp matches the superchain default in the neighbouring `superchain.yaml` file, we should NOT add the override at all.

IMO we tackle these in a followup issue / PRs. This PR is reasonably urgent, because it will cause tests to incorrectly fail on in flight standard chain PRs.

**Comment by mds1** [comment]
We should also perform a check that all existing files are consistent with the conventions above and modify them if so
