### ISSUE TITLE
fix: avoid skipping checks for conduit chains

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-registry#178]
From https://github.com/ethereum-optimism/superchain-registry/pull/107#pullrequestreview-1998488407

> Approving and merging this PR, but we'll later need to investigate the Genesis test failures that are currently being skipped for Metal Sepolia, Metal Mainnet, and Superlumio Mainnet
> 
> We also are skipping the L2OO tests for those chains + Mode Sepolia, and should confirm that's ok.

**Comment by geoknee** [comment]
https://www.notion.so/oplabs/Superchain-Genesis-Hash-checks-60e173e9fb0c43e88a81d0666cb3d582

**Comment by geoknee** [comment]
The key thing is if ecotone is activated at or before genesis. this affects genesis block because of these lines https://github.com/ethereum-optimism/op-geth/blob/9617f2a7dd0ab80c468d6e474e3cc26be9572c97/core/genesis.go#L538-L552

**Comment by geoknee** [comment]
Here's one way of fixing this https://github.com/ethereum-optimism/superchain-registry/compare/gk/skip-default-hf-times?expand=1. 

The idea is to not specify hardfork times in a superchain wide way any more. Every chain has to specify their own hard fork times.

Pros:
* remove a lot of complexity in superchain registry Go code
* genesis hash checks pass again
* no downstream changes necessary, op-geth and op-node inspect the per chain values anyway

Cons:
* we may need to go back and get the correct values for chains, I don't think we can tell if we have them correct at the moment
* more repetition across configs (not a big deal, I think)
* no longer enshrining "upgrade together" flow into the data structures. But, we can probably still do that using other tooling, and write whatever checks and balances we want. 


Here is the PR where the behaviour was added https://github.com/ethereum-optimism/superchain-registry/pull/101
