### ISSUE TITLE
Update add-chain script to support chains with fault proofs

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-optimism/superchain-registry#222]
Currently the add-chain go module expects a single, rigid list of contract names/addresses in the `monorepo/deployments/.deploy` input file. Chains with fault proofs will have a different set of contracts: L2OO will be absent and others (e.g. Dispute Game Factory) will be present. The add-chain script should support these types of chains in addition to chains without fault proofs. The `add-chain/e2e_test.go` setup will need to be modified to test multiple types of chains and input formats.

Reference for a chain with fault proofs: [link](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/extra/addresses/sepolia/op.json)

**Additional Context**

* [Github thread](https://github.com/ethereum-optimism/superchain-registry/pull/204#discussion_r1587855333)

**Comment by BlocksOnAChain** [comment]
@bitwiseguy @geoknee ok to close this one?

**Comment by geoknee** [comment]
No we want this one to stay open.
