### ISSUE TITLE
CheckSecurityConfigs: Check integrity of the implementations

### ISSUE THREAD

**Issue by zchn** [ethereum-optimism/superchain-registry#33]
In https://github.com/ethereum-optimism/superchain-registry/pull/31, we automated the checking of OP Chain access control integrity. To further improve the checks, we should also check the integrity of the implementations, i.e. whether the OP Chains are using governance approved protocol implementations and whether they are using a non-deprecated version.

**Comment by pegahcarter** [comment]
This can probably be done by validation of the implementation `version()`.

**Comment by geoknee** [comment]
This will be covered by https://github.com/ethereum-optimism/superchain-registry/issues/289
