### ISSUE TITLE
validation: add drift detection on `SystemConfig.startBlock()`

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#371]
We want to
* store the _original_ `startBlock` value in the superchain registry somewhere (this could be part of the add-chain tooling)
  * get the `Initialized` logs from the system config contract, and use the oldest block number
* have a validation check which queries the current value and ensures it is equal to the original value.

**Comment by geoknee** [comment]
No mention of this in the BHIC spec. 

This is an example of something that can change in principle in future, so might be something (therefore) to check in the registry. 

However, if we can be sure that this parameter cannot change after key handover, does that mean we don't need to check it going forward?

**Comment by geoknee** [comment]
There's a general question about how much we should be relying on BHIC check + key handover to ensure a chain is still "standard".

**Comment by geoknee** [comment]
From my investigations, it seems that the l1 block time stored in the `rollup.json` file (and therefore read by `op-node`) is decided by when the getting-started script is run https://github.com/ethereum-optimism/optimism/blob/d510910381d99660295f99e4eccd553df5829df6/packages/contracts-bedrock/scripts/getting-started/config.sh#L26-L29, or even when the op-node genesis creation command is run: https://github.com/ethereum-optimism/optimism/blob/547ea72d9849e13ce169fd31df0f9197651b3f86/op-node/cmd/genesis/cmd.go#L189-L190.

**Comment by geoknee** [comment]
The system config value [is documented as](https://github.com/ethereum-optimism/optimism/blob/d510910381d99660295f99e4eccd553df5829df6/packages/contracts-bedrock/src/L1/SystemConfig.sol#L77-L79)

_    /// @notice Storage slot for block at which the op-node can start searching for logs from._.

**Comment by geoknee** [comment]
* The check in the registry should be that the off-chain start block value is earlier than or equal to the on chain value.
* Chains that have the off-chain value later than the on chain value will fail the test. They then need to manually alter their config (i.e. the rollup.json) to push it back earlier and resubmit the PR
* We probably need a bit more work to get drift detection in place for the on-chain value, we need to understand how the start block has changed on chain over time.
* Existing chains which fail will need to be excluded, or we communicate with them about updating their offchain config values.

**Comment by bitwiseguy** [comment]
Existing chains that fail the offChain <= onChain start block check:
* OP mainnet
  * offChain: [17_422_590](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/op.toml#L21)
  * onChain: [17_422_444](https://etherscan.io/address/0x229047fed2591dbec1eF1118d64F7aF3dB9EB290#readProxyContract)
  * 1st deposit tx: [17_423_165](https://etherscan.io/txs?a=0xbEb5Fc579115071764c7423A4f12eDde41f106Ed&p=386)
* OP sepolia
  * offChain: [4_071_408](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/op.toml#L21)
  * onChain: [4_071_248](https://sepolia.etherscan.io/address/0x034edD2A225f7f429A63E0f1D2084B9E0A93b538#readProxyContract)
  * 1st deposit tx: [4_113_914](https://sepolia.etherscan.io/txs?a=0x16Fc5058F25648194471939df75CF27A2fdC48BC&p=102)

**Comment by geoknee** [comment]
Yeah I think we could make those updates, I wonder if we want to run some manual sync tests with those changes to make triple sure? cc @sebastianst 

We can also bake in a couple of exclusions for these if we want to unblock.

**Comment by sebastianst** [comment]
Looks good to me to rewind the off-chain values to the on-chain ones. We could start a sync-test with this change applied for extra validation 👍🏻

**Comment by bitwiseguy** [comment]
Decided to leave the configs as-is and just perform an extra check when offChain > onChain to confirm there were no TransactionDeposited events emitted from the OptimismPortal contract during that gap
