### ISSUE TITLE
improvements following live insertion walkthrough

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#404]
* Why is this PR failing https://github.com/ethereum-optimism/superchain-registry/pull/402 ?
* We should run the contract versions check first, and if it fails we print a message and don't bother running the remaining tests which depend on the contract versions being correct

**Comment by sbvegan** [comment]
It looks like this was the issue: https://github.com/ethereum-optimism/superchain-registry/pull/409

We'll have them rebase their PR and the error should go away
