### ISSUE TITLE
ci: reroute validation errors/alerts caused by 3rd party components

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-optimism/superchain-registry#428]
Currently the validation checks run as part of CI jobs that block PRs from being merged if there are failures. Also, the hourly CI job runs these same checks and reports failures to the `#notify-ci-failures` channel, which is generally used to detect failures of `ethereum-optimism` code, not external 3rd party software. Open PRs should not be blocked by issues with chains that are irrelevant to the PR.

We should make the following changes:
1. Create a new, independent validation CI job that runs every hour and routes its notifications to a new slack channel
2. Adjust the current "open PR" CI job so that it only runs validation checks on chains whose config changes as part of that PR (i.e. a new chain added, or existing chain modified). We should be able to run `git diff` to detect which chains have been changed, then leverage the `just validate <chain-id>` command to validation only those chains.

Separate standard-candidate chain validation checks:
* Set of validation checks they must pass to join the registry - should run in CI and block pr merge if there are failures
* Separate set of validation checks that inform what they need to fix before becoming standard
  * perhaps manually triggered github action

**Comment by geoknee** [comment]
We also only need to run genesis checks as a one off when the chain is added, there isn't much point running drift detection on this.

**Comment by geoknee** [comment]
Design doc in progress here https://www.notion.so/oplabs/Superchain-Registry-Check-Routing-0f4f734c159a48c3abfc0d6a82f07faf

**Comment by geoknee** [comment]
An early step towards closing this ticket would be:
* add a `just ` command for running _only_ unit tests. This can use a regex to filter out validation checks
* change the CI config so that unit tests run in a different step to validation checks

**Comment by geoknee** [comment]
A subsequent step would be to:
* detect which chains were modified using `git diff`
* only run validation checks for those chains
