### ISSUE TITLE
docs: outline config changes related to renaming plasma to alt-da 

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-optimism/superchain-registry#432]
Since renaming the plasma feature to alt-da and replacing all references to plasma in the code will cause breaking changes, we should document how chains using the deprecated plasma feature can migrate to alt-da. Changes to document include config cli params and env vars + version of op-node that includes the breaking change.

**Comment by geoknee** [comment]
We could prepare a PR with the breaking changes soon, and this would help inform the documentation. 

The guiding principle should be to make minimal changes such that superchain-registry does not mention plasma at all.

**Comment by bitwiseguy** [comment]
WIP notion doc [here](https://www.notion.so/oplabs/Migrating-plasma-users-altda-0b9c886cf20c4f8995c0e48ac5a3270b)

**Comment by geoknee** [comment]
@bitwiseguy can we call this done? Let's coordinate with devrel about communicating this to the appropriate partners.

**Comment by bitwiseguy** [comment]
Completed this after merging monorepo commit [here](https://github.com/ethereum-optimism/optimism/commit/0bb2ff57c8133f1e3983820c0bf238001eca119b) and superchain-registry commit [here](https://github.com/ethereum-optimism/superchain-registry/commit/0c96567855b9a605bd8028b63d86b7296e6ec305)
