### ISSUE TITLE
Do not use overrides in `LoadOPStackRollupConfig`

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#458]
All information should be stored in and read from the superchain registry. 

* update the op-node `LoadOPStackRollupConfig` function
* update the add-chain module to capture the data
* possibly update existing config toml files to backport missing data

We can lean on the rollup config diff checker tool to help guide us with this (we should not have any net diff in the configs being exported, I think). 

My preference would be to keep `LoadOPStackRollupConfig` very transparent and backport any necessary data into the individual config files in the registry.

**Comment by bitwiseguy** [comment]
Completed via [this monorepo pr](https://github.com/ethereum-optimism/optimism/pull/11459) and [this superchain-registry pr](https://github.com/ethereum-optimism/superchain-registry/pull/469).
