### ISSUE TITLE
remove Just as a dependency for adding chains

### ISSUE THREAD

**Issue by tessr** [ethereum-optimism/superchain-registry#461]
In our chain onboarding sessions so far, partner teams typically don't have `just` installed, and sometimes have trouble installing it. 

We should see if we can remove `just` as a dependency, at least for adding chains so that partner teams don't need to install a new dependency, if not for all our workflows. 

One option could be to add a Makefile that handles _only_ the tasks that partner teams might need to run.

**Comment by alfonso-op** [comment]
We're now actively migrating from Makefiles to just, so closing as won't do.
