### ISSUE TITLE
Perform L1 Bytecode checking for contracts with immutables

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#493]
These contracts are not checked for bytecode match 
```
		"AnchorStateRegistryProxy",
		"DelayedWETHProxy",
		"DisputeGameFactoryProxy",
		"FaultDisputeGame",
		"MIPS",
```
because of their use of immutables, we cannot use a static bytecode hash across all chains to do the validation. 

Suggested fix is to declare the `immutableReferences` for the contract version in question (we get this from the relevant op-contracts tag compiler artifacts) as well as the hash of the _masked_ bytecode (masking here means replacing all immutable references with zeros. Then, the validation check pulls the bytecode from chain, masks it using the immutable references, hashes the result and compares against the expectation.

**Comment by vdamle** [comment]
I'd like to note that the original description mentioned `"DisputeGameFactoryProxy"` as a contract that contains immutables. However, the contract does not have immutables (amended description to remove this contract)
