### ISSUE TITLE
Handle error when adding a frontier chain with no deploy-config

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#601]
We should modify this code:
https://github.com/ethereum-optimism/superchain-registry/blob/acb5f92d8fbfe60aa5a75c082b6f73aac90bf7d1/add-chain/main.go#L196-L201

so that if the chain is frontier and not a standard candidate, we swallow the error and print out a meaningful message since we do not require this information for chains that won't ever be subject to the genesis-allocs validation.

**Comment by alfonso-op** [comment]
Closing in favor of tracking this issue in https://github.com/ethereum-optimism/superchain-registry/issues/696
