### ISSUE TITLE
validation: move exceptions into toml file

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-optimism/superchain-registry#637]
Validation test exceptions are currently coded in golang files. Governance prefers these exceptions to be moved into toml files to make each exception more explicit and easy to read. The go tests can parse the toml file and make exceptions based on what it reads from toml

**Comment by sbvegan** [comment]
Okay we aligned that because we're referring to L2 discrepancies, they don't matter from the perspective of the current gov-approved TOMLS are only L1. So no action is needed on this part, thanks sam!
