### ISSUE TITLE
Get `CheckSecurityConfigs` passing again.

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#87]
Some changes were made on chain which should be reflected in the registry. https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-registry/337/workflows/0c87fd15-22a3-4718-a198-87de3904de84/jobs/1334

**Comment by mds1** [comment]
> I think we should consider running the CI checks nightly, since I only discovered this CI failure on a pull request with unrelated changes.

This seems like a good idea to me so I created https://github.com/ethereum-optimism/superchain-registry/issues/89
