### ISSUE TITLE
Run `CheckSecurityConfigs` on a scheduled job

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-registry#89]
From https://github.com/ethereum-optimism/superchain-registry/issues/87

> Some changes were made on chain which should be reflected in the registry. https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-registry/337/workflows/0c87fd15-22a3-4718-a198-87de3904de84/jobs/1334
> 
> I think we should consider running the CI checks nightly, since I only discovered this CI failure on a pull request with unrelated changes.

These checks should be pretty fast and cheap to execute, so we can execute them on a scheduled job fairly frequently to catch issues faster. We should also make sure failures of this scheduled job send an alert

**Comment by geoknee** [comment]
We can hook it into the #notify-ci-failures slack channel, too.
