### ISSUE TITLE
feat: Standardize configs on a single format

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/superchain-registry#93]
## Overview

Currently, we have multiple file formats in the superchain registry for configurations, which is unnecessary. This makes it more difficult to pull in the `superchain-registry` as a dependency while reading the raw files, without a wrapper [like the Golang one](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/superchain.go#L108-L131). It's also very awkward to write bindings for the `superchain-registry` because of this - in Rust, for example, needing to support `YAML` + `JSON` requires two crate dependencies.

We should standardize on a single file format.

**Comment by geoknee** [comment]
I'm not aware of a reason for having two separate formats in the repo, so standardising to one seems pretty fair. Can you expand on why you favour JSON? I know YAML has some drawbacks, but just want to highlight that comments can be pretty useful, especially for timestamps:

https://github.com/ethereum-optimism/superchain-registry/blob/9828415051c62b9cbaef3862558dbd54b3a7833e/superchain/configs/goerli-dev-0/superchain.yaml#L8

I guess we lose that with JSON, although the comment content could be embedded as data.

It seems to me that the migration you are suggesting could probably be largely automated, and wouldn't break any of the interfaces exported by the Go module or the npm package. So the cost/benefit analysis looks reasonable to me.

**Comment by mds1** [comment]
Agreed on standardizing, though like @geoknee I also dislike that JSON prevents us from adding comments. My personal preference is standardizing around TOML since YAML has some oddities, but I'm ok with YAML too

**Comment by clabby** [comment]
JSON was mainly due to it's native support in most language that wrap the registry, but I prefer TOML personally. So long as we don't use several formats, I'm not super opinionated :)

**Comment by sebastianst** [comment]
Also a big fan of standardizing this. Although I prefer YAML over JSON, I think we need JSONs because they're used in NPM packages. Is that correct @roninjin10 ?

**Comment by roninjin10** [comment]
If we make this update it will break things downstream that depend on it like docs and https://github.com/ethereum-optimism/optimism/pull/9041

**Comment by mds1** [comment]
Documenting that we came to consensus on using TOML. We can use [yj](https://github.com/sclevine/yj), or replace jq with [yq](https://github.com/mikefarah/yq), for minimal diffs in scripts using jq. Foundry is in the [process](https://github.com/foundry-rs/foundry/pull/7317) of adding TOML parsing cheatcodes as well
