### ISSUE TITLE
Consider extracting exported data into the filesystem itself

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#96]
This will make it available to future consumers of the repo that want to access such data _not_ through the Go module.

See also #36 and #93

Example: 

This code was added for validation, but included in the `superchain` module in case it may be useful to consumers of that module:
https://github.com/ethereum-optimism/superchain-registry/blob/a87e7b7a2f774051885eb9032f9d0150a4cf4746/superchain/params.go#L40

It should _either_ not be exported at all, and housed in the `validation` module, _or_ extracted into a suitable e.g. `toml` or `json` file.

**Comment by BlocksOnAChain** [comment]
@geoknee ok to close this one?
